inputs = [
  'mstore(W1_Y_LOC, mod(calldataload(data_ptr), q))',
  'mstore(W1_X_LOC, mod(calldataload(add(data_ptr, 0x20)), q))',
  'mstore(W2_Y_LOC, mod(calldataload(add(data_ptr, 0x40)), q))',
  'mstore(W2_X_LOC, mod(calldataload(add(data_ptr, 0x60)), q))',
  'mstore(W3_Y_LOC, mod(calldataload(add(data_ptr, 0x80)), q))',
  'mstore(W3_X_LOC, mod(calldataload(add(data_ptr, 0xa0)), q))',
  'mstore(W4_Y_LOC, mod(calldataload(add(data_ptr, 0xc0)), q))',
  'mstore(W4_X_LOC, mod(calldataload(add(data_ptr, 0xe0)), q))',
  'mstore(S_Y_LOC, mod(calldataload(add(data_ptr, 0x100)), q))',
  'mstore(S_X_LOC, mod(calldataload(add(data_ptr, 0x120)), q))',
  'mstore(Z_Y_LOC, mod(calldataload(add(data_ptr, 0x140)), q))',
  'mstore(Z_X_LOC, mod(calldataload(add(data_ptr, 0x160)), q))',
  'mstore(Z_LOOKUP_Y_LOC, mod(calldataload(add(data_ptr, 0x180)), q))',
  'mstore(Z_LOOKUP_X_LOC, mod(calldataload(add(data_ptr, 0x1a0)), q))',
  'mstore(T1_Y_LOC, mod(calldataload(add(data_ptr, 0x1c0)), q))',
  'mstore(T1_X_LOC, mod(calldataload(add(data_ptr, 0x1e0)), q))',
  'mstore(T2_Y_LOC, mod(calldataload(add(data_ptr, 0x200)), q))',
  'mstore(T2_X_LOC, mod(calldataload(add(data_ptr, 0x220)), q))',
  'mstore(T3_Y_LOC, mod(calldataload(add(data_ptr, 0x240)), q))',
  'mstore(T3_X_LOC, mod(calldataload(add(data_ptr, 0x260)), q))',
  'mstore(T4_Y_LOC, mod(calldataload(add(data_ptr, 0x280)), q))',
  'mstore(T4_X_LOC, mod(calldataload(add(data_ptr, 0x2a0)), q))',
  'mstore(W1_EVAL_LOC, mod(calldataload(add(data_ptr, 0x2c0)), p))',
  'mstore(W2_EVAL_LOC, mod(calldataload(add(data_ptr, 0x2e0)), p))',
  'mstore(W3_EVAL_LOC, mod(calldataload(add(data_ptr, 0x300)), p))',
  'mstore(W4_EVAL_LOC, mod(calldataload(add(data_ptr, 0x320)), p))',
  'mstore(S_EVAL_LOC, mod(calldataload(add(data_ptr, 0x340)), p))',
  'mstore(Z_EVAL_LOC, mod(calldataload(add(data_ptr, 0x360)), p))',
  'mstore(Z_LOOKUP_EVAL_LOC, mod(calldataload(add(data_ptr, 0x380)), p))',
  'mstore(Q1_EVAL_LOC, mod(calldataload(add(data_ptr, 0x3a0)), p))',
  'mstore(Q2_EVAL_LOC, mod(calldataload(add(data_ptr, 0x3c0)), p))',
  'mstore(Q3_EVAL_LOC, mod(calldataload(add(data_ptr, 0x3e0)), p))',
  'mstore(Q4_EVAL_LOC, mod(calldataload(add(data_ptr, 0x400)), p))',
  'mstore(QM_EVAL_LOC, mod(calldataload(add(data_ptr, 0x420)), p))',
  'mstore(QC_EVAL_LOC, mod(calldataload(add(data_ptr, 0x440)), p))',
  'mstore(QARITH_EVAL_LOC, mod(calldataload(add(data_ptr, 0x460)), p))',
  'mstore(QSORT_EVAL_LOC, mod(calldataload(add(data_ptr, 0x480)), p))',
  'mstore(QELLIPTIC_EVAL_LOC, mod(calldataload(add(data_ptr, 0x4a0)), p))',
  'mstore(QAUX_EVAL_LOC, mod(calldataload(add(data_ptr, 0x4c0)), p))',
  'mstore(SIGMA1_EVAL_LOC, mod(calldataload(add(data_ptr, 0x4e0)), p))',
  'mstore(SIGMA2_EVAL_LOC, mod(calldataload(add(data_ptr, 0x500)), p))',
  'mstore(SIGMA3_EVAL_LOC, mod(calldataload(add(data_ptr, 0x520)), p))',
  'mstore(SIGMA4_EVAL_LOC, mod(calldataload(add(data_ptr, 0x540)), p))',
  'mstore(TABLE1_EVAL_LOC, mod(calldataload(add(data_ptr, 0x560)), p))',
  'mstore(TABLE2_EVAL_LOC, mod(calldataload(add(data_ptr, 0x580)), p))',
  'mstore(TABLE3_EVAL_LOC, mod(calldataload(add(data_ptr, 0x5a0)), p))',
  'mstore(TABLE4_EVAL_LOC, mod(calldataload(add(data_ptr, 0x5c0)), p))',
  'mstore(TABLE_TYPE_EVAL_LOC, mod(calldataload(add(data_ptr, 0x5e0)), p))',
  'mstore(ID1_EVAL_LOC, mod(calldataload(add(data_ptr, 0x600)), p))',
  'mstore(ID2_EVAL_LOC, mod(calldataload(add(data_ptr, 0x620)), p))',
  'mstore(ID3_EVAL_LOC, mod(calldataload(add(data_ptr, 0x640)), p))',
  'mstore(ID4_EVAL_LOC, mod(calldataload(add(data_ptr, 0x660)), p))',
  'mstore(W1_OMEGA_EVAL_LOC, mod(calldataload(add(data_ptr, 0x680)), p))',
  'mstore(W2_OMEGA_EVAL_LOC, mod(calldataload(add(data_ptr, 0x6a0)), p))',
  'mstore(W3_OMEGA_EVAL_LOC, mod(calldataload(add(data_ptr, 0x6c0)), p))',
  'mstore(W4_OMEGA_EVAL_LOC, mod(calldataload(add(data_ptr, 0x6e0)), p))',
  'mstore(S_OMEGA_EVAL_LOC, mod(calldataload(add(data_ptr, 0x700)), p))',
  'mstore(Z_OMEGA_EVAL_LOC, mod(calldataload(add(data_ptr, 0x720)), p))',
  'mstore(Z_LOOKUP_OMEGA_EVAL_LOC, mod(calldataload(add(data_ptr, 0x740)), p))',
  'mstore(TABLE1_OMEGA_EVAL_LOC, mod(calldataload(add(data_ptr, 0x760)), p))',
  'mstore(TABLE2_OMEGA_EVAL_LOC, mod(calldataload(add(data_ptr, 0x780)), p))',
  'mstore(TABLE3_OMEGA_EVAL_LOC, mod(calldataload(add(data_ptr, 0x7a0)), p))',
  'mstore(TABLE4_OMEGA_EVAL_LOC, mod(calldataload(add(data_ptr, 0x7c0)), p))',
  'mstore(PI_Z_Y_LOC, mod(calldataload(add(data_ptr, 0x7e0)), q))',
  'mstore(PI_Z_X_LOC, mod(calldataload(add(data_ptr, 0x800)), q))',
  'mstore(PI_Z_OMEGA_Y_LOC, mod(calldataload(add(data_ptr, 0x820)), q))',
  'mstore(PI_Z_OMEGA_X_LOC, mod(calldataload(add(data_ptr, 0x840)), q))',
]

for row in inputs:
  location = row.split('(')[1].split(',')[0].split('_LOC')[0]
  
  print('INPUT_' + location + ',')
